# Default Config
# 
# minigames-mode: true/false
# Set this to "true" if you want a chatreport to show every message from a user since the plugin has started.
# If you set it to "false", a chatreport will only show messages from a user of the last 15 minutes
# 
# server: Servername
# Set the servername here. It will show up on the webpage.
# 
# URL: URL to webpage
# Set the URL to your webpage here. It will be send to the user after doing /chatreport <player>.
# The reportid will be added at the end.
# 
# bypass-with-beginning-chat: 
# If yout set an custom letter here, every message beginning with that char won't be logged if the player has the permission you set one line down.
# set it to '' (empty) will log every message. This is helpful for plugins which handles messages like that as a staffChat or something like that.
# 
# Cleanup
# enabled: false -- set it to true and it will delete messages older than 14 days (change with "since")
# since: 14 -- delete messages older than ... days
# cleanup will run after serverstart
# 
minigames-mode: false
server: 'Servername'
URL: http://freecraft.eu/chatlog/?report=
bypass-with-beginning-char: '#'
bypass-with-permission: 'ChatLog.canbypass'
Cleanup:
  enabled: false
  since: 14