name: ChatLog
descriptipn: Chatlog to report players
version: 1.13.1
api-version: 1.18
author: McLive
website: www.freecraft.eu

main: eu.mclive.ChatLog.ChatLog

commands:
  chatreport:
    description: Chatlog generator for reporting players