name: ChatLog
version: 1.1
descriptipn: Chatlog to report players
author: McLive
website: www.freecraft.eu

main: eu.mclive.ChatLog.ChatLog
commands:
  chatreport:
    description: Chatlog to report players