name: ChatLog
descriptipn: Chatlog generator to report players
version: 1.13.4
api-version: 1.13
author: McLive
website: www.freecraft.eu

main: eu.mclive.ChatLog.ChatLog

commands:
  chatreport:
    aliases: [chatlog]
    description: Generate a chatlog to report players